name: band_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  geocoding: ^3.0.0
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  kakao_flutter_sdk: ^1.9.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/