name: band_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  kakao_flutter_sdk: ^1.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/